receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: localhost:4317

service:
  telemetry:
    logs:
      encoding: json
      level: warn
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    
