before:
  hooks:
    - go mod download
monorepo:
  tag_prefix: cmd/builder/
  dir: cmd/builder
builds:
  - flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X go.opentelemetry.io/collector/cmd/builder/internal.version={{.Version}}
      - -X go.opentelemetry.io/collector/cmd/builder/internal.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64le
    ignore:
      - goos: windows
        goarch: arm64
    binary: ocb
brews:
  - name: ocb
    tap:
      owner: open-telemetry
      name: homebrew-tap
    homepage: https://opentelemetry.io/docs/collector/custom-collector/
    description: This program generates a custom OpenTelemetry Collector from a given configuration.
    license: Apache-2.0
    folder: Formula
    dependencies:
      - name: go
        type: optional
    test: |
      system "#{bin}/ocb version"
release:
  github:
    owner: open-telemetry
    name: opentelemetry-collector
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
