receivers:
  opencensus:
    endpoint: 0.0.0.0:55678
  zipkin:
    endpoint: 0.0.0.0:9412

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: promexample
    const_labels:
      label1: value1
  logging:

  zipkin:
    url: "http://0.0.0.0:9411/api/v2/spans"

  jaeger_grpc:
    endpoint: jaeger-all-in-one:14250

# Alternatively, use jaeger_thrift_http with the settings below. In this case
# update the list of exporters on the traces pipeline.
#
#  jaeger_thrift_http:
#    url: http://jaeger-all-in-one:14268/api/traces

processors:
  batch:
  tail_sampling:
    decision_wait: 10s
    num_traces: 100
    expected_new_traces_per_sec: 10
    policies:
      [
      {
        name: test-policy-1,
        type: string_probabilistic_attribute,
        string_probabilistic_attribute: {key: "http.status_code", values: ["500::1.0", "200::0.1"]}
      }
      ]

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [opencensus, zipkin]
      exporters: [logging, zipkin, jaeger_grpc]
      processors: [batch,tail_sampling]
    metrics:
      receivers: [opencensus]
      exporters: [logging,prometheus]

