receivers:
  otlp:
    protocols:
      grpc:
  kafkametrics:
    protocol_version: 2.0.0
    scrapers:
      - brokers
      - topics
      - consumers
    brokers: "35.193.145.20:9092"

exporters:
  otlp:
    endpoint: "otel-collector:4317"
    insecure: true
  logging:
    loglevel: debug

processors:
  batch:

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [batch]
      exporters: [otlp, logging]
    metrics:
      receivers: [ otlp, kafkametrics ]
      processors: [batch]
      exporters: [otlp, logging]
