"$schema": http://json-schema.org/draft-04/schema#
id: opentelemetry.io/collector/config/configcompression/configcompression
title: Type
type: string
enum:
- gzip
- zlib
- deflate
- snappy
- zstd
- none
- ''
default: 'none'