# Enable debug level to see output of "logging" exporter
log-level: DEBUG

receivers:
  opencensus:
    endpoint: 0.0.0.0:55678
  jaeger:
    protocols:
      thrift-http:
        endpoint: "0.0.0.0:14268"


exporters:
  opencensus:
    endpoint: "otel-collector:55678"
  logging:

processors:
  batch:
  queued-retry:

pipelines:
  traces:
    receivers: [opencensus, jaeger]
    exporters: [opencensus, logging]
    processors: [batch, queued-retry]
