name: Builder - Integration tests

on:
  # on changes to the main branch touching the builder
  push:
    branches: [ main ]
    paths:
      - 'cmd/builder/**'

  # on PRs touching the builder
  pull_request:
    branches: [ main ]
    paths:
      - 'cmd/builder/**'
  
  # once a day at 6:17 AM UTC
  schedule:
    - cron: '17 6 * * *'

  # manual execution
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Patch builder config
        shell: bash
        run: |
          cd ./cmd/builder
          cat >> cmd/builder/internal/config/default.yaml <<EOF
          replaces:
            - go.opentelemetry.io/collector => ../../
            - go.opentelemetry.io/collector/semconv => ../../semconv
            - go.opentelemetry.io/collector/pdata => ../../pdata
          EOF
          ./test/test.sh
      - name: Test
        shell: bash
        run: |
          cd ./cmd/builder
          ./test/test.sh
